# Generated by Django 4.0.3 on 2022-07-13 20:53

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OfflineFile',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.commoninfo')),
                ('file_type', models.CharField(blank=True, choices=[('Image', 'Image'), ('Video', 'Video'), ('App', 'App')], max_length=30, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.utils.generate_offline_filename)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField(null=True)),
            ],
            bases=('core.commoninfo',),
        ),
        migrations.CreateModel(
            name='ChunkedUploadFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('offset', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Incomplete'), (2, 'Complete')], default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(max_length=255, null=True, upload_to=core.utils.generate_chunked_filename, verbose_name='file')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
