# Generated by Django 4.0.3 on 2023-04-22 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkeduploadfile',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offlinefile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('Image', 'Image'), ('Video', 'Video'), ('Apk', 'Apk'), ('Document', 'Document')], max_length=30, null=True),
        ),
    ]
